In [1]:
!pip install hydrobr

Requirement already satisfied: hydrobr in /home/priscylla/anaconda3/envs/city-graph/lib/python3.10/site-packages (0.1.1)
Requirement already satisfied: tqdm>=4.31 in /home/priscylla/anaconda3/envs/city-graph/lib/python3.10/site-packages (from hydrobr) (4.65.0)
Requirement already satisfied: pandas>=0.25 in /home/priscylla/anaconda3/envs/city-graph/lib/python3.10/site-packages (from hydrobr) (1.5.3)
Requirement already satisfied: requests>=2.21 in /home/priscylla/anaconda3/envs/city-graph/lib/python3.10/site-packages (from hydrobr) (2.28.1)
Requirement already satisfied: plotly>=4.6.0 in /home/priscylla/anaconda3/envs/city-graph/lib/python3.10/site-packages (from hydrobr) (5.14.0)
Requirement already satisfied: numpy>=1.21.0 in /home/priscylla/anaconda3/envs/city-graph/lib/python3.10/site-packages (from pandas>=0.25->hydrobr) (1.24.2)
Requirement already satisfied: pytz>=2020.1 in /home/priscylla/anaconda3/envs/city-graph/lib/python3.10/site-packages (from pandas>=0.25->hydrobr) (2022.7)
Requirement already satisfied: python-dateutil>=2.8.1 in /home/priscylla/anaconda3/envs/city-graph/lib/python3.10/site-packages (from pandas>=0.25->hydrobr) (2.8.2)
Requirement already satisfied: packaging in /home/priscylla/anaconda3/envs/city-graph/lib/python3.10/site-packages (from plotly>=4.6.0->hydrobr) (23.0)
Requirement already satisfied: tenacity>=6.2.0 in /home/priscylla/anaconda3/envs/city-graph/lib/python3.10/site-packages (from plotly>=4.6.0->hydrobr) (8.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /home/priscylla/anaconda3/envs/city-graph/lib/python3.10/site-packages (from requests>=2.21->hydrobr) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /home/priscylla/anaconda3/envs/city-graph/lib/python3.10/site-packages (from requests>=2.21->hydrobr) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/priscylla/anaconda3/envs/city-graph/lib/python3.10/site-packages (from requests>=2.21->hydrobr) (1.26.15)
Requirement already satisfied: charset-normalizer<3,>=2 in /home/priscylla/anaconda3/envs/city-graph/lib/python3.10/site-packages (from requests>=2.21->hydrobr) (2.0.4)
Requirement already satisfied: six>=1.5 in /home/priscylla/anaconda3/envs/city-graph/lib/python3.10/site-packages (from python-dateutil>=2.8.1->pandas>=0.25->hydrobr) (1.16.0)

In [2]:
import requests
import json
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
import hydrobr

In [4]:
inmet_stations = hydrobr.get_data.INMET.list_stations(station_type='automatic')

In [5]:
inmet_stations.head()

,Code,Type,Name,State,Latitude,Longitude,Height,Start Operation,End Operation
0,A422,Automatic,ABROLHOS,BA,-17.96305555,-38.70333333,20.93,2008-07-20 21:00:00-03:00,In operation
1,A360,Automatic,ACARAU,CE,-3.1211111,-40.08722221,67.15,2009-04-21 21:00:00-03:00,In operation
2,A657,Automatic,AFONSO CLAUDIO,ES,-20.10416666,-41.10694444,507.48,2011-09-23 21:00:00-03:00,In operation
3,A908,Automatic,AGUA BOA,MT,-14.01638888,-52.21166666,440,2006-12-15 21:00:00-03:00,In operation
4,A756,Automatic,AGUA CLARA,MS,-20.44444444,-52.87583332,323.63,2010-08-13 21:00:00-03:00,In operation

In [6]:
stations_by_state = inmet_stations.groupby('State')

In [7]:
stations_sp = stations_by_state.get_group('SP')

In [8]:
stations_sp

,Code,Type,Name,State,Latitude,Longitude,Height,Start Operation,End Operation
40,A736,Automatic,ARIRANHA,SP,-21.13305554,-48.84055555,525.44,2007-11-12 21:00:00-03:00,In operation
43,A725,Automatic,AVARE,SP,-23.10166666,-48.9411111,776.36,2006-09-21 21:00:00-03:00,In operation
53,A741,Automatic,BARRA BONITA,SP,-22.4711111,-48.5575,533.68,2008-04-23 21:00:00-03:00,In operation
55,A746,Automatic,BARRA DO TURVO,SP,-24.96277777,-48.41638888,659.89,2008-07-02 21:00:00-03:00,In operation
57,A748,Automatic,BARRETOS,SP,-20.55916666,-48.54499999,534.36,2010-06-18 21:00:00-03:00,In operation
58,A755,Automatic,BARUERI,SP,-23.52388888,-46.86944443,776.5,2011-03-28 21:00:00-03:00,In operation
60,A705,Automatic,BAURU,SP,-22.358052,-49.028877,636.17,2001-08-29 21:00:00-03:00,In operation
61,A764,Automatic,BEBEDOURO,SP,-20.94805555,-48.47138888,542,2016-10-26 21:00:00-03:00,In operation
67,A765,Automatic,BERTIOGA,SP,-23.84472221,-46.14333333,5,2017-01-31 21:00:00-03:00,In operation
74,A744,Automatic,BRAGANCA PAULISTA,SP,-22.95194444,-46.53055554,891,2017-12-19 21:00:00-03:00,In operation
88,A769,Automatic,CACHOEIRA PAULISTA,SP,-22.68888888,-45.00555555,586,2017-10-19 21:00:00-03:00,In operation
107,A706,Automatic,CAMPOS DO JORDAO,SP,-22.75027777,-45.60388888,1662.95,2002-03-12 21:00:00-03:00,In operation
127,A738,Automatic,CASA BRANCA,SP,-21.78055554,-47.07527777,734.15,2007-06-24 21:00:00-03:00,In operation
177,A762,Automatic,DRACENA,SP,-21.45777777,-51.55222222,720,2016-11-02 21:00:00-03:00,In operation
200,A708,Automatic,FRANCA,SP,-20.58444444,-47.38249999,1002.74,2002-12-11 22:00:00-02:00,In operation
224,A737,Automatic,IBITINGA,SP,-21.85555555,-48.79972221,496.75,2007-11-08 21:00:00-03:00,In operation
227,A712,Automatic,IGUAPE,SP,-24.67166666,-47.54583333,2.7,2006-07-19 21:00:00-03:00,In operation
247,A714,Automatic,ITAPEVA,SP,-23.98194443,-48.88583333,743.33,2006-07-24 21:00:00-03:00,In operation
249,A739,Automatic,ITAPIRA,SP,-22.415,-46.80527777,634.89,2007-11-04 21:00:00-03:00,In operation
259,A753,Automatic,ITUVERAVA,SP,-20.35972222,-47.77527777,610.58,2008-07-16 21:00:00-03:00,In operation
266,A733,Automatic,JALES,SP,-20.165,-50.59499999,460.44,2007-08-21 21:00:00-03:00,In operation
276,A735,Automatic,JOSE BONIFACIO,SP,-21.08555555,-49.92027777,408.35,2007-09-02 21:00:00-03:00,In operation
288,A727,Automatic,LINS,SP,-21.66611111,-49.73472221,460.65,2006-09-19 21:00:00-03:00,In operation
312,A763,Automatic,MARILIA,SP,-22.235222,-49.965111,660,2017-05-14 21:00:00-03:00,In operation
384,A726,Automatic,PIRACICABA,SP,-22.70305555,-47.62333332,566.46,2006-09-25 21:00:00-03:00,In operation
407,A747,Automatic,PRADOPOLIS,SP,-21.33833333,-48.11388888,540.41,2008-04-21 21:00:00-03:00,In operation
411,A707,Automatic,PRESIDENTE PRUDENTE,SP,-22.11999999,-51.40861111,431.92,2003-02-03 22:00:00-02:00,In operation
419,A718,Automatic,RANCHARIA,SP,-22.37277777,-50.97472221,398.75,2006-08-31 21:00:00-03:00,In operation
423,A766,Automatic,REGISTRO,SP,-24.53305554,-47.86416666,35,2017-02-08 21:00:00-03:00,In operation
470,A711,Automatic,SAO CARLOS,SP,-21.980353,-47.883927,859.29,2006-09-03 21:00:00-03:00,In operation
483,A740,Automatic,SAO LUIZ DO PARAITINGA,SP,-23.22833332,-45.41694443,862.3,2007-10-31 21:00:00-03:00,In operation
489,A771,Automatic,SAO PAULO - INTERLAGOS,SP,-23.724501,-46.677501,771,2018-03-13 21:00:00-03:00,In operation
490,A701,Automatic,SAO PAULO - MIRANTE,SP,-23.49638888,-46.61999999,785.64,2006-07-24 21:00:00-03:00,In operation
494,A770,Automatic,SAO SIMAO,SP,-21.46111111,-47.57944443,620,2019-07-02 21:00:00-03:00,In operation
516,A713,Automatic,SOROCABA,SP,-23.4261111,-47.58555555,609.33,2006-08-21 21:00:00-03:00,In operation
523,A728,Automatic,TAUBATE,SP,-23.04166666,-45.52083332,582.26,2006-12-19 21:00:00-03:00,In operation
538,A768,Automatic,TUPA,SP,-21.927251,-50.490251,498,2017-05-11 21:00:00-03:00,In operation
553,A734,Automatic,VALPARAISO,SP,-21.31916666,-50.93027777,381.9,2007-08-29 21:00:00-03:00,In operation

In [9]:
stations_sp = stations_sp.loc[(stations_sp['Name']=='SAO PAULO - MIRANTE') | (stations_sp['Name']== 'SAO PAULO - INTERLAGOS') | (stations_sp['Name']== 'BARUERI')]
stations_sp

,Code,Type,Name,State,Latitude,Longitude,Height,Start Operation,End Operation
58,A755,Automatic,BARUERI,SP,-23.52388888,-46.86944443,776.5,2011-03-28 21:00:00-03:00,In operation
489,A771,Automatic,SAO PAULO - INTERLAGOS,SP,-23.724501,-46.677501,771,2018-03-13 21:00:00-03:00,In operation
490,A701,Automatic,SAO PAULO - MIRANTE,SP,-23.49638888,-46.61999999,785.64,2006-07-24 21:00:00-03:00,In operation

In [10]:
stations_sp['Latitude']=stations_sp['Latitude'].astype('float64')
stations_sp['Longitude']=stations_sp['Longitude'].astype('float64')
stations_sp.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3 entries, 58 to 490
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Code             3 non-null      object
 1   Type             3 non-null      object
 2   Name             3 non-null      object
 3   State            3 non-null      object
 4   Latitude         3 non-null      float64
 5   Longitude        3 non-null      float64
 6   Height           3 non-null      object
 7   Start Operation  3 non-null      object
 8   End Operation    3 non-null      object
dtypes: float64(2), object(7)
memory usage: 240.0+ bytes

In [16]:
resposta = requests.get('http://apitempo.inmet.gov.br/estacao/2017-01-01/2017-01-31/A701')
resposta

In [11]:
def get_inmet_hourly_data(station):
    
    station = str(station)
    
    #res06 = requests.get('https://apitempo.inmet.gov.br/estacao/2006-01-01/2006-12-31/' + station)
    res07 = requests.get('https://apitempo.inmet.gov.br/estacao/2007-01-01/2007-12-31/' + station)
    res08 = requests.get('https://apitempo.inmet.gov.br/estacao/2008-01-01/2008-12-31/' + station)
    res09 = requests.get('https://apitempo.inmet.gov.br/estacao/2009-01-01/2009-12-31/' + station)
    res10 = requests.get('https://apitempo.inmet.gov.br/estacao/2010-01-01/2010-12-31/' + station)
    res11 = requests.get('https://apitempo.inmet.gov.br/estacao/2011-01-01/2011-12-31/' + station)
    res12 = requests.get('https://apitempo.inmet.gov.br/estacao/2012-01-01/2012-12-31/' + station)
    res13 = requests.get('https://apitempo.inmet.gov.br/estacao/2013-01-01/2013-12-31/' + station)
    res14 = requests.get('https://apitempo.inmet.gov.br/estacao/2014-01-01/2014-12-31/' + station)
    res15 = requests.get('https://apitempo.inmet.gov.br/estacao/2015-01-01/2015-12-31/' + station)
    res16 = requests.get('https://apitempo.inmet.gov.br/estacao/2016-01-01/2016-12-31/' + station)
    res17 = requests.get('https://apitempo.inmet.gov.br/estacao/2017-01-01/2017-12-31/' + station)

    responses = []
    #responses.append(pd.DataFrame(json.loads(res06.text)))
    responses.append(pd.DataFrame(json.loads(res07.text)))
    responses.append(pd.DataFrame(json.loads(res08.text)))
    responses.append(pd.DataFrame(json.loads(res09.text)))
    responses.append(pd.DataFrame(json.loads(res10.text)))
    responses.append(pd.DataFrame(json.loads(res11.text)))
    responses.append(pd.DataFrame(json.loads(res12.text)))
    responses.append(pd.DataFrame(json.loads(res13.text)))
    responses.append(pd.DataFrame(json.loads(res14.text)))
    responses.append(pd.DataFrame(json.loads(res15.text)))
    responses.append(pd.DataFrame(json.loads(res16.text)))
    responses.append(pd.DataFrame(json.loads(res17.text)))
    
    data_station = pd.concat(responses)
    return data_station

In [12]:
# A771 interlagos (2018-03-13 21:00:00-03:00) fora do range de crimes que temos
# A701 Mirante (2006-07-24 21:00:00-03:00) sem os primeiros 7 meses de 2006

In [13]:
data_station = get_inmet_hourly_data('A701')

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [ ]:
data_station